## This notebook is dedicated to revising some of the most frequently used operations in Numpy
***

In [2]:
import numpy as np

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
mylist = [1,2,3]

In [10]:
myarr = np.array(mylist)

In [12]:
myarr

array([1, 2, 3])

In [15]:
# broadcasting feature of numpy
print(np.ones(5) + 5)
print(np.ones(5) - 5)
print(np.ones(5) * 5)
print(np.ones(5) / 5)

[6. 6. 6. 6. 6.]
[-4. -4. -4. -4. -4.]
[5. 5. 5. 5. 5.]
[0.2 0.2 0.2 0.2 0.2]


In [17]:
# arrange the array as a sequence with a start, stop and stepsize
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [20]:
# very similar to arange, except here you get to decide how many elements you want
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [22]:
# create identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
# creating array with random numbers
np.random.rand(5)   # this function gets a random number from a uniform distribution

array([0.43796063, 0.96134612, 0.12984897, 0.470666  , 0.90962394])

In [29]:
# sample random numbers from a standard normal distribution with mean 0 and std dev as 1
ranarr = np.random.randn(25)

In [35]:
# reshaping the array, -1 means that numpy will calculate
# what should be the second dimension of that array
ranarr.reshape(5,-1).shape

(5, 5)

In [38]:
ranarr

array([ 1.37210222, -0.4761784 ,  0.39654746,  0.46403637, -0.7277484 ,
       -0.34385121,  0.27548099, -0.28203298, -1.63100059, -1.03981716,
        0.72373401,  1.02439453, -0.15965406,  0.13106694,  1.04439644,
       -0.04557699, -1.78663134,  0.7459583 , -0.77576444, -0.38624923,
        0.27804079,  1.20451872,  1.15148958,  0.67170848, -0.79141359])

In [37]:
# max and min vs argmax and argmin
print(ranarr.max())
print(ranarr.min())    # returns the element
print(ranarr.argmax()) # returns the index
print(ranarr.argmin())

1.372102221885528
-1.7866313405482444
0
16


In [39]:
# slicing an array still refers to the original array
ori_arr = np.ones(5)

In [40]:
sliced_arr = ori_arr[:3]

In [42]:
sliced_arr

array([1., 1., 1.])

In [46]:
sliced_arr += 14

In [49]:
sliced_arr

array([15., 15., 15.])

In [51]:
ori_arr   # changes are made in the original array

array([15., 15., 15.,  1.,  1.])

In [52]:
# to avoid this, we need to first make a copy
dup_arr = ori_arr.copy()

In [54]:
dup_arr

array([15., 15., 15.,  1.,  1.])

In [56]:
dup_arr += 10

In [58]:
dup_arr

array([25., 25., 25., 11., 11.])

In [60]:
ori_arr  # now the original array is not affected

array([15., 15., 15.,  1.,  1.])

In [62]:
# conditional arrays
print(ori_arr > 5)

[ True  True  True False False]


In [64]:
print(ori_arr ==15)

[ True  True  True False False]


In [65]:
print(ori_arr[ori_arr> 5])

[15. 15. 15.]
